[build]
  command = "npm install --legacy-peer-deps && vite build"  # Runs your build script
  publish = "dist"          # Vite's default output folder
  # publish = "build"       # Use this for Create React App

[context.production.environment]
  VITE_API_URL = "https://api.yoursite.com"  # Example env var for Vite

[[headers]]
  # Ensure JS/CSS files have correct MIME types
  for = "/*"
  [headers.values]
    Content-Type = "text/javascript"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  # SPA fallback for React Router
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Remove if not using Next.js